
################################################################################
# Title: WSP Status Extraction Script
# Author: Stephen Finnis
# Date Created: November 4, 2025
# Date Modified: Feb 2026 by Erika to add French versions

# Description:
# This script status information for Pacific salmon Conservation Units (CUs)
# using SQL logic originally written for a database query. The SQL code has been
# adapted to run in R using "DuckDB". The original SQL code is saved as a text
# file and found in the SQL folder

# The source data comes from the CU_PROFILE_VW database view from NuSEDS, which
# has been exported as an Excel file ('cu_profile_vw.xlsx')

# Each SQL query targets a specific species or life history type and
# retrieves Wild Salmon Policy (WSP) Rapid and Integrated Status assessments.

# Output:
# - Each query result is saved as a named data frame (e.g., coho_status)
# - Each data frame is written to a separate CSV file (e.g., coho_status.csv)
# - Files are saved in the output folder with lowercase, underscore-separated names

# Important:
# The original SQL code contains multiple SELECT statements.
# DuckDB (i.e, the dbGetQuery function) can only execute ONE SELECT query at a time.
# Therefore, each query is run separately and stored in its own named
# data frame for inspection and export.

# Usage:
# 1. Ensure the Excel file 'cu_profile_vw.xlsx' is in your working directory.
# 2. Run the script to generate and inspect data frames.
# 3. CSVs will be written to the output folder
################################################################################


# Install and load required packages
#install.packages("DBI")
#install.packages("duckdb")
#install.packages("readxl")
#install.packages("readr")

library(DBI)
library(duckdb)
library(readxl)
library(readr)

# Clear the environment
rm(list = ls(all.names = TRUE))

# Create a duckdb connection
con = dbConnect(duckdb())

# Read the required Excel file into a data frame
cu_profile_df = read_excel("data/cu_profile_vw.xlsx")

# Register the data frame as a duckdb table
duckdb_register(con, "CU_PROFILE_VW", cu_profile_df)

# Define SQL queries and output names
queries = list(
  CK_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
           INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Chinook'
    ORDER BY FULL_CU_IN ASC
  ",
  CK_SBC_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Chinook'
      AND FULL_CU_IN IN (
        'CK-01','CK-02','CK-03','CK-04','CK-05','CK-06','CK-07','CK-08','CK-09','CK-10',
        'CK-11','CK-12','CK-13','CK-14','CK-15','CK-16','CK-17','CK-18','CK-19','CK-20',
        'CK-21','CK-22','CK-25','CK-27','CK-28','CK-29','CK-31','CK-32','CK-33','CK-34',
        'CK-35','CK-82','CK-83','CK-9005','CK-9008'
      )
    ORDER BY FULL_CU_IN ASC
  ",
  CM_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Chum'
    ORDER BY FULL_CU_IN ASC
  ",
  CO_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Coho'
    ORDER BY FULL_CU_IN ASC
  ",
  PKE_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Pink' AND LH_TYPE = 'Even Year'
    ORDER BY FULL_CU_IN ASC
  ",
  PKO_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Pink' AND LH_TYPE = 'Odd Year'
    ORDER BY FULL_CU_IN ASC
  ",
  SEL_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Sockeye' AND LH_TYPE = 'Lake Type'
    ORDER BY FULL_CU_IN ASC
  ",
  SER_CU_STATUS_En = "
    SELECT CU_NAME, FULL_CU_IN, SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
           LH_TYPE AS LIFE_HISTORY_TYPE, SPECIES, CU_TYPE,
           WSP_RAPID_STATUS, WSP_RAPID_CONFIDENCE,
           CASE WHEN WSP_RAPID_STATUS IS NULL THEN NULL ELSE WSP_RAPID_STATUS_YEAR END AS WSP_RAPID_STATUS_YEAR,
          INTEGRATED_STATUS AS WSP_INTEGRATED_STATUS, INTEGRATED_STATUS_YEAR AS WSP_INTEGRATED_STATUS_YEAR
    FROM CU_PROFILE_VW
    WHERE SPECIES = 'Sockeye' AND LH_TYPE = 'River Type'
    ORDER BY FULL_CU_IN ASC
  ",
  CK_CU_STATUS_Fr = "SELECT
  CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Chinook'
ORDER BY FULL_CU_IN ASC;",

  CK_SBC_CU_STATUS_Fr = "SELECT
CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Chinook'
AND
FULL_CU_IN IN ('CK-01',
'CK-02',
'CK-03',
'CK-04',
'CK-05',
'CK-06',
'CK-07',
'CK-08',
'CK-09',
'CK-10',
'CK-11',
'CK-12',
'CK-13',
'CK-14',
'CK-15',
'CK-16',
'CK-17',
'CK-18',
'CK-19',
'CK-20',
'CK-21',
'CK-22',
'CK-25',
'CK-27',
'CK-28',
'CK-29',
'CK-31',
'CK-32',
'CK-33',
'CK-34',
'CK-35',
'CK-82',
'CK-83',
'CK-9005',
'CK-9008')
ORDER BY FULL_CU_IN ASC;",

  CM_CU_STATUS_Fr = "SELECT
CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Chum'
ORDER BY FULL_CU_IN ASC;",

  CO_CU_STATUS_Fr = "SELECT
  CU_NAME_FR AS NOM_UC,
  FULL_CU_IN AS INDICE_UC,
  SUBSTR(FULL_CU_IN, 1, 2) AS SP_QUAL,
  LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
  SPECIES_FR AS ESPÈCES,
  CU_TYPE_FR AS TYPE_CU,
  WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
  WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
  CASE
  WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
  ELSE WSP_RAPID_STATUS_YEAR
  END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
  CASE
  WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
  WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
  WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
  WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
  WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
  WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
  WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
  WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
  WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
  WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
  WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
  WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
  ELSE INTEGRATED_STATUS
  END AS STATUT_INTÉGRÉ_PSS,
  INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
  FROM
  CU_PROFILE_VW
  WHERE
  SPECIES='Coho'
  ORDER BY FULL_CU_IN ASC;",

  PKE_CU_STATUS_Fr = "SELECT
CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Pink'
AND
LH_TYPE='Even Year'
ORDER BY FULL_CU_IN ASC;",

  PKO_CU_STATUS_Fr = "
SELECT
CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Pink'
AND
LH_TYPE='Odd Year'
ORDER BY FULL_CU_IN ASC;",

  SEL_CU_STATUS_Fr = "SELECT
CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Sockeye'
AND
LH_TYPE='Lake Type'
ORDER BY FULL_CU_IN ASC;",

  SER_CU_STATUS_Fr = "SELECT
CU_NAME_FR AS NOM_UC,
FULL_CU_IN AS INDICE_UC,
SUBSTR(FULL_CU_IN, 1, 3) AS SP_QUAL,
LH_TYPE_FR AS TYPE_DE_CYCLE_BIOLOGIQUE,
SPECIES_FR AS ESPÈCES,
CU_TYPE_FR AS TYPE_CU,
WSP_RAPID_STATUS_FR AS 'ÉVALUATION RAPIDE DE L’ÉTAT PSS',
WSP_RAPID_CONFIDENCE_FR AS 'ÉVALUATION RAPIDE DE LA FIABILITÉ PSS',
CASE
WHEN WSP_RAPID_STATUS_FR IS NULL THEN NULL
ELSE WSP_RAPID_STATUS_YEAR
END AS 'ANNÉE DE L’ÉVALUATION RAPIDE DE L’ÉTAT PSS',
CASE
        WHEN INTEGRATED_STATUS = 'RED/AMBER' THEN 'Rouge/Ambre'
        WHEN INTEGRATED_STATUS = 'TBD' THEN 'À déterminer '
        WHEN INTEGRATED_STATUS = 'AMBER/RED' THEN 'Ambre/Rouge'
        WHEN INTEGRATED_STATUS = 'AMBER' THEN 'Ambre'
        WHEN INTEGRATED_STATUS = 'GREEN/RED' THEN 'Vert/Rouge'
        WHEN INTEGRATED_STATUS = 'RED/AMBER/GREEN' THEN 'Rouge/Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'AMBER/GREEN' THEN 'Ambre/Vert'
        WHEN INTEGRATED_STATUS = 'GREEN' THEN ' Vert'
        WHEN INTEGRATED_STATUS = 'DD' THEN 'Données insuffisantes'
        WHEN INTEGRATED_STATUS = 'GREEN/AMBER' THEN 'Vert/Ambre'
        WHEN INTEGRATED_STATUS = 'AMBER/RED/GREEN' THEN 'Ambre/Rouge/Vert'
        WHEN INTEGRATED_STATUS = 'RED' THEN 'Rouge'
        ELSE INTEGRATED_STATUS
    END AS STATUT_INTÉGRÉ_PSS,
INTEGRATED_STATUS_YEAR AS ANNÉE_DU_STATUT_INTÉGRÉ_PSS
FROM
CU_PROFILE_VW
WHERE
SPECIES='Sockeye'
AND
LH_TYPE='River Type'
ORDER BY FULL_CU_IN ASC;"

)

# Run each query and store results in named data frames
status_results = list()
for (name in names(queries)) {
  status_results[[name]] = dbGetQuery(con, queries[[name]])
}

# Inspect results in RStudio
# Example: View(status_results$coho_status)

dir.create("output", showWarnings = FALSE, recursive = TRUE)

for (nm in names(status_results)) {
  filename <- file.path("output", paste0(nm, ".csv"))
  # UTF-8 with BOM & blanks for missing values
  write_excel_csv(status_results[[nm]], filename, na = "")
}

# Disconnect from DuckDB
dbDisconnect(con, shutdown = TRUE)

